# Makefile for cv.tex using cv-style.sty and biblatex/biber

NAME=cv
TEX=${NAME}.tex
STYLE=cv-style.sty
BIB=citations.bib
PDF=${NAME}.pdf

# Default target
all: ${PDF}

# Rule to build the PDF
${PDF}: ${TEX} ${STYLE} ${BIB}
	@echo "Compiling ${NAME}.tex..."
	latexmk -pdf ${TEX}

# Clean auxiliary files generated by LaTeX
clean:
	@echo "Cleaning auxiliary files..."
	latexmk -c ${TEX}
	rm -f *~ 

# Remove everything including the PDF
distclean: clean
	@echo "Removing PDF..."
	rm -f ${PDF}

# Force rebuild
rebuild: distclean all

# Phony targets
.PHONY: all clean distclean rebuild
